-- DATOS LISTAS_VIDEOS
-- 1 LISTA POR USUARIO CON 2 VIDEOS DE OTROS USUARIOS

USE hernandezjimenez;

INSERT INTO listas_videos VALUES
-- LISTA DE VIDEOS DE RUBIUS
(0, 'IK01V1oED9w'),
(0, 'h9i9DBH-ll8'),

-- LISTA DE VIDEOS DE AURON
(1, 'TviCcF2yo6o'),
(1, 'ZHPEQcMVRT4'),

-- LISTA DE VIDEOS DE WISMICHU
(2, 'WFCWiviBVQM'),
(2, 'ZNqDla-AntY'),

-- LISTA DE VIDEOS DE IBAI
(3, 'ZNqDla-AntY'),
(3, '2I9P3MIx1Wg'),

-- LISTA DE VIDEOS DE TRECE
(4, 'h9i9DBH-ll8'),
(4, 'WFCWiviBVQM');